spring:
  profiles: 
    active:
    - dev
--
spring:
  profiles: dev #开发环境
  application: 
    name: microservicecloud-config-atzkhy-dev
--
spring:
  profiles: dev #测试环境
  application: 
    name: microservicecloud-config-atzkhy-test
#必须保存为UTF-8格式1
